In [16]:
import theano
import numpy

In [17]:
import theano.tensor as T

In [31]:
a = theano.tensor.vector() # declare variable

In [32]:
out = a + a ** 10               # build symbolic expression

In [33]:
f = theano.function([a], out)   # compile function

In [34]:
print(f([0, 1, 2]))

[    0.     2.  1026.]


In [98]:
y=numpy.array([ 1,  3,  2,  4,  2])

In [99]:
y

array([1, 3, 2, 4, 2])

In [100]:
d = numpy.arange(y.shape[0]),y

In [101]:
d

(array([0, 1, 2, 3, 4]), array([1, 3, 2, 4, 2]))

In [102]:
LP = numpy.random.rand(5,5)

In [103]:
print(LP)

[[ 0.85678778  0.49679186  0.5765878   0.68917208  0.92769785]
 [ 0.5815817   0.68811381  0.92655873  0.66113232  0.93917525]
 [ 0.80681506  0.76572725  0.62675176  0.26629886  0.34193998]
 [ 0.47266346  0.21910899  0.8766583   0.74306865  0.61306006]
 [ 0.64851643  0.79025409  0.55604542  0.99108054  0.65342087]]


In [104]:
result = LP [numpy.arange(y.shape[0]), y]

In [105]:
print(result)

[ 0.49679186  0.66113232  0.62675176  0.61306006  0.55604542]
